### ISSUE TITLE
skrypt bnnyDrop  nie działa

### ISSUE THREAD

**Issue by TheVersusxPro** [xNorbig/bnnyDrop#3]
Twój skrypt wywali mi takie błędy przez co serwer mi się wyłącza:

```[20:01:23 INFO]: Starting GS4 status listener
[20:01:23 INFO]: Query running on 0.0.0.0:27465
[20:01:23 INFO]: [Skript] Checking for the latest version of Skript...
[20:01:23 INFO]: [Skript] An internal error occurred while checking for the latest version of Skript. Please refer to the server log for details.
[20:01:23 ERROR]: #!#!
[20:01:23 ERROR]: #!#! [Skript] Severe Error:
[20:01:23 ERROR]: #!#! Unexpected error while checking for a new version of Skript
[20:01:23 ERROR]: #!#!
[20:01:23 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[20:01:23 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[20:01:23 ERROR]: #!#! and check whether this error has already been reported.
[20:01:23 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[20:01:23 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[20:01:23 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[20:01:23 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[20:01:23 ERROR]: #!#!
[20:01:23 ERROR]: #!#! Stack trace:
[20:01:23 ERROR]: #!#! javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
[20:01:23 ERROR]: #!#!at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596)
[20:01:23 ERROR]: #!#!at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
[20:01:23 ERROR]: #!#!at ch.njol.skript.Updater.getChangelogs(Updater.java:286)
[20:01:23 ERROR]: #!#!at ch.njol.skript.Updater$2.run(Updater.java:210)
[20:01:23 ERROR]: #!#!at java.lang.Thread.run(Thread.java:745)
[20:01:23 ERROR]: #!#!
[20:01:23 ERROR]: #!#! Version Information:
[20:01:23 ERROR]: #!#!Skript: 2.1.2
[20:01:23 ERROR]: #!#!Bukkit: 1.8.8-R0.1-SNAPSHOT
[20:01:23 ERROR]: #!#!Minecraft: 1.8.8
[20:01:23 ERROR]: #!#!Java: 1.8.0_91
[20:01:23 ERROR]: #!#!
[20:01:23 ERROR]: #!#! Running CraftBukkit: false
[20:01:23 ERROR]: #!#!
[20:01:23 ERROR]: #!#! Current node: null
[20:01:23 ERROR]: #!#! Current item: null
[20:01:23 ERROR]: #!#!
[20:01:23 ERROR]: #!#! Thread: Skript update thread
[20:01:23 ERROR]: #!#!
[20:01:23 ERROR]: #!#! End of Error.
[20:01:23 ERROR]: #!#!
[20:01:23 INFO]: [Skript] You're currently running the latest stable version of Skript.
[20:01:25 WARN]: [Skript] Possible name conflict of variables {name%loop-index%} and {name} (there might be more conflicts). (case.sk, line 149: set {_name%loop-index%} to loop-value')
[20:01:30 WARN]: [Skript] Possible name conflict of variables {item9} and {item%loop-number-2 + 1%} (there might be more conflicts). (case.sk, line 226: set {_item9} to random element out of {case::%{_name}%::itemlist::*}')
[20:01:30 WARN]: [Skript] Possible name conflict of variables {item5} and {item%loop-number-2 + 1%} (there might be more conflicts). (case.sk, line 231: broadcast "{@tag} {@general}Gracz {@important}%{_player}% {@general}wylosowal {@important}%{_item5}% {@general}ze skrzyni {@important}%{_name}%{@general}. Gratulacje!"')
[20:01:36 ERROR]: [Skript] 'bnnyDrop_sendMessage(player: player, value: text, arg-1: text, arg-2: text)' is not a text (srop ze stone.sk, line 1: function bnnyDrop_sendMessage(player: player, value: text, arg-1: text, arg-2: text):')
[20:01:36 ERROR]: [Skript] 'bnnyDrop_checkPermission(player: player, arg-1: text, arg-2: text, notify: boolean) :: boolean' is not a text (srop ze stone.sk, line 8: function bnnyDrop_checkPermission(player: player, arg-1: text, arg-2: text, notify: boolean) :: boolean:')
[20:01:36 ERROR]: [Skript] 'bnnyDrop_reloadPlayer(player: player)' is not a text (srop ze stone.sk, line 21: function bnnyDrop_reloadPlayer(player: player):')
[20:01:36 ERROR]: [Skript] 'bnnyDrop_toggleDrop(player: player, item: text)' is not a text (srop ze stone.sk, line 35: function bnnyDrop_toggleDrop(player: player, item: text):')
[20:01:36 ERROR]: [Skript] 'bnnyDrop_checkPermission(player, "drop", "", true) is true' is not a boolean (yes/no) (srop ze stone.sk, line 59: if bnnyDrop_checkPermission(player, "drop", "", true) is true:')
[20:01:36 ERROR]: [Skript] 'bnnyDrop_checkPermission(player, "statistics", "", true) is true' is not a boolean (yes/no) (srop ze stone.sk, line 138: if bnnyDrop_checkPermission(player, "statistics", "", true) is true:')
[20:01:37 ERROR]: [Skript] 'bnnyDrop_checkPermission(player, "statistics.others", "", true) is true' is not a boolean (yes/no) (srop ze stone.sk, line 142: if bnnyDrop_checkPermission(player, "statistics.others", "", true) is true:')
[20:01:37 ERROR]: [Skript] 'replace all "{0}" with "%{_item::%loop-value%}%" in <...>' can only accept a single text, not more (srop ze stone.sk, line 152: replace all "{0}" with "%{_item::%loop-value%}%" in {_lore::%loop-value%::*}')
[20:01:37 ERROR]: [Skript] 'replace all "{0}" with "%{_player}%" in <...>' can only accept a single text, not more (srop ze stone.sk, line 166: replace all "{0}" with "%{_player}%" in {_lore::%loop-value%::*}')
[20:01:37 ERROR]: [Skript] 'replace all "{0}" with "%{_item::stone}%" in <...>' can only accept a single text, not more (srop ze stone.sk, line 168: replace all "{0}" with "%{_item::stone}%" in {_lore::%loop-value%::*}')
[20:01:37 ERROR]: [Skript] 'replace all "{0}" with "%{_item::points}%" in <...>' can only accept a single text, not more (srop ze stone.sk, line 170: replace all "{0}" with "%{_item::points}%" in {_lore::%loop-value%::*}')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {lore::header} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 175: format slot {_guiitem::header::slot} parsed as number-1 of player with {_guiitem::header::item} parsed as item named colored {_guiitem::header::name} with lore colored {_lore::header} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::header::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 175: format slot {_guiitem::header::slot} parsed as number-1 of player with {_guiitem::header::item} parsed as item named colored {_guiitem::header::name} with lore colored {_lore::header} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::header::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 175: format slot {_guiitem::header::slot} parsed as number-1 of player with {_guiitem::header::item} parsed as item named colored {_guiitem::header::name} with lore colored {_lore::header} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::header::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 175: format slot {_guiitem::header::slot} parsed as number-1 of player with {_guiitem::header::item} parsed as item named colored {_guiitem::header::name} with lore colored {_lore::header} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {lore::coal} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 176: format slot {_guiitem::drop.coal::slot} parsed as number-1 of player with {_guiitem::drop.coal::item} parsed as item named colored {_guiitem::drop.coal::name} with lore colored {_lore::coal} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.coal::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 176: format slot {_guiitem::drop.coal::slot} parsed as number-1 of player with {_guiitem::drop.coal::item} parsed as item named colored {_guiitem::drop.coal::name} with lore colored {_lore::coal} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.coal::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 176: format slot {_guiitem::drop.coal::slot} parsed as number-1 of player with {_guiitem::drop.coal::item} parsed as item named colored {_guiitem::drop.coal::name} with lore colored {_lore::coal} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.coal::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 176: format slot {_guiitem::drop.coal::slot} parsed as number-1 of player with {_guiitem::drop.coal::item} parsed as item named colored {_guiitem::drop.coal::name} with lore colored {_lore::coal} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {lore::iron} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 177: format slot {_guiitem::drop.iron::slot} parsed as number-1 of player with {_guiitem::drop.iron::item} parsed as item named colored {_guiitem::drop.iron::name} with lore colored {_lore::iron} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.iron::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 177: format slot {_guiitem::drop.iron::slot} parsed as number-1 of player with {_guiitem::drop.iron::item} parsed as item named colored {_guiitem::drop.iron::name} with lore colored {_lore::iron} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.iron::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 177: format slot {_guiitem::drop.iron::slot} parsed as number-1 of player with {_guiitem::drop.iron::item} parsed as item named colored {_guiitem::drop.iron::name} with lore colored {_lore::iron} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.iron::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 177: format slot {_guiitem::drop.iron::slot} parsed as number-1 of player with {_guiitem::drop.iron::item} parsed as item named colored {_guiitem::drop.iron::name} with lore colored {_lore::iron} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {lore::lapis} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 178: format slot {_guiitem::drop.lapis::slot} parsed as number-1 of player with {_guiitem::drop.lapis::item} parsed as item named colored {_guiitem::drop.lapis::name} with lore colored {_lore::lapis} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.lapis::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 178: format slot {_guiitem::drop.lapis::slot} parsed as number-1 of player with {_guiitem::drop.lapis::item} parsed as item named colored {_guiitem::drop.lapis::name} with lore colored {_lore::lapis} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.lapis::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 178: format slot {_guiitem::drop.lapis::slot} parsed as number-1 of player with {_guiitem::drop.lapis::item} parsed as item named colored {_guiitem::drop.lapis::name} with lore colored {_lore::lapis} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.lapis::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 178: format slot {_guiitem::drop.lapis::slot} parsed as number-1 of player with {_guiitem::drop.lapis::item} parsed as item named colored {_guiitem::drop.lapis::name} with lore colored {_lore::lapis} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {lore::gold} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 179: format slot {_guiitem::drop.gold::slot} parsed as number-1 of player with {_guiitem::drop.gold::item} parsed as item named colored {_guiitem::drop.gold::name} with lore colored {_lore::gold} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.gold::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 179: format slot {_guiitem::drop.gold::slot} parsed as number-1 of player with {_guiitem::drop.gold::item} parsed as item named colored {_guiitem::drop.gold::name} with lore colored {_lore::gold} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.gold::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 179: format slot {_guiitem::drop.gold::slot} parsed as number-1 of player with {_guiitem::drop.gold::item} parsed as item named colored {_guiitem::drop.gold::name} with lore colored {_lore::gold} to be unstealable')
[20:01:37 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.gold::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 179: format slot {_guiitem::drop.gold::slot} parsed as number-1 of player with {_guiitem::drop.gold::item} parsed as item named colored {_guiitem::drop.gold::name} with lore colored {_lore::gold} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {lore::diamond} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 180: format slot {_guiitem::drop.diamond::slot} parsed as number-1 of player with {_guiitem::drop.diamond::item} parsed as item named colored {_guiitem::drop.diamond::name} with lore colored {_lore::diamond} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.diamond::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 180: format slot {_guiitem::drop.diamond::slot} parsed as number-1 of player with {_guiitem::drop.diamond::item} parsed as item named colored {_guiitem::drop.diamond::name} with lore colored {_lore::diamond} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.diamond::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 180: format slot {_guiitem::drop.diamond::slot} parsed as number-1 of player with {_guiitem::drop.diamond::item} parsed as item named colored {_guiitem::drop.diamond::name} with lore colored {_lore::diamond} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.diamond::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 180: format slot {_guiitem::drop.diamond::slot} parsed as number-1 of player with {_guiitem::drop.diamond::item} parsed as item named colored {_guiitem::drop.diamond::name} with lore colored {_lore::diamond} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {lore::redstone} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 181: format slot {_guiitem::drop.redstone::slot} parsed as number-1 of player with {_guiitem::drop.redstone::item} parsed as item named colored {_guiitem::drop.redstone::name} with lore colored {_lore::redstone} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.redstone::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 181: format slot {_guiitem::drop.redstone::slot} parsed as number-1 of player with {_guiitem::drop.redstone::item} parsed as item named colored {_guiitem::drop.redstone::name} with lore colored {_lore::redstone} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.redstone::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 181: format slot {_guiitem::drop.redstone::slot} parsed as number-1 of player with {_guiitem::drop.redstone::item} parsed as item named colored {_guiitem::drop.redstone::name} with lore colored {_lore::redstone} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.redstone::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 181: format slot {_guiitem::drop.redstone::slot} parsed as number-1 of player with {_guiitem::drop.redstone::item} parsed as item named colored {_guiitem::drop.redstone::name} with lore colored {_lore::redstone} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {lore::emerald} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 182: format slot {_guiitem::drop.emerald::slot} parsed as number-1 of player with {_guiitem::drop.emerald::item} parsed as item named colored {_guiitem::drop.emerald::name} with lore colored {_lore::emerald} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.emerald::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 182: format slot {_guiitem::drop.emerald::slot} parsed as number-1 of player with {_guiitem::drop.emerald::item} parsed as item named colored {_guiitem::drop.emerald::name} with lore colored {_lore::emerald} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.emerald::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 182: format slot {_guiitem::drop.emerald::slot} parsed as number-1 of player with {_guiitem::drop.emerald::item} parsed as item named colored {_guiitem::drop.emerald::name} with lore colored {_lore::emerald} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::drop.emerald::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 182: format slot {_guiitem::drop.emerald::slot} parsed as number-1 of player with {_guiitem::drop.emerald::item} parsed as item named colored {_guiitem::drop.emerald::name} with lore colored {_lore::emerald} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {lore::special.stone} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 183: format slot {_guiitem::special.stone::slot} parsed as number-1 of player with {_guiitem::special.stone::item} parsed as item named colored {_guiitem::special.stone::name} with lore colored {_lore::special.stone} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::special.stone::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 183: format slot {_guiitem::special.stone::slot} parsed as number-1 of player with {_guiitem::special.stone::item} parsed as item named colored {_guiitem::special.stone::name} with lore colored {_lore::special.stone} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::special.stone::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 183: format slot {_guiitem::special.stone::slot} parsed as number-1 of player with {_guiitem::special.stone::item} parsed as item named colored {_guiitem::special.stone::name} with lore colored {_lore::special.stone} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::special.stone::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 183: format slot {_guiitem::special.stone::slot} parsed as number-1 of player with {_guiitem::special.stone::item} parsed as item named colored {_guiitem::special.stone::name} with lore colored {_lore::special.stone} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {lore::special.points} and {lore::%loop-value-1%} (there might be more conflicts). (srop ze stone.sk, line 184: format slot {_guiitem::special.points::slot} parsed as number-1 of player with {_guiitem::special.points::item} parsed as item named colored {_guiitem::special.points::name} with lore colored {_lore::special.points} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::special.points::name} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 184: format slot {_guiitem::special.points::slot} parsed as number-1 of player with {_guiitem::special.points::item} parsed as item named colored {_guiitem::special.points::name} with lore colored {_lore::special.points} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::special.points::item} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 184: format slot {_guiitem::special.points::slot} parsed as number-1 of player with {_guiitem::special.points::item} parsed as item named colored {_guiitem::special.points::name} with lore colored {_lore::special.points} to be unstealable')
[20:01:38 WARN]: [Skript] Possible name conflict of variables {guiitem::special.points::slot} and {guiitem::%loop-value-1%::%loop-value-2%} (there might be more conflicts). (srop ze stone.sk, line 184: format slot {_guiitem::special.points::slot} parsed as number-1 of player with {_guiitem::special.points::item} parsed as item named colored {_guiitem::special.points::name} with lore colored {_lore::special.points} to be unstealable')
[20:01:38 ERROR]: [Skript] 'bnnyDrop_checkPermission(player, "top10", "", true) is true' is not a boolean (yes/no) (srop ze stone.sk, line 189: if bnnyDrop_checkPermission(player, "top10", "", true) is true:')
[20:01:38 ERROR]: [Skript] 'bnnyDrop_reloadPlayer(loop-player)' is not a boolean (yes/no) (srop ze stone.sk, line 258: bnnyDrop_reloadPlayer(loop-player)')
[20:02:23 FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[20:02:23 FATAL]: Considering it to be crashed, server will forcibly shutdown.
[20:02:24 ERROR]: This crash report has been saved to: /home/e127696/pliki/./crash-reports/crash-2017-07-31_20.02.24-server.txt```

Proszę o pomoc, twój skrypt zrobił na mnie wrażenie lecz nie działa : P

**Comment by xNorbig** [comment]
Definitywnie zaktualizuj Skript. Wersja 2.1.2 nie posiada funkcji, a tutaj są one użyte.

https://github.com/bensku/Skript/releases/download/dev29/Skript.jar
